//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mats.rc
//
#define ID_ABOUT                        9
#define IDR_MENU1                       101
#define IDI_MAIN                        113
#define IDI_SMINACTIVE                  116
#define IDI_SMACTIVE                    117
#define IDB_BITMAP1                     118
#define IDD_OPTIONS                     119
#define IDR_MENU2                       120
#define IDD_CHANNELS                    121
#define IDR_TOOLBAR1                    122
#define IDR_TOOLBAR2                    126
#define IDR_MENU3                       131
#define IDR_MENU4                       132
#define IDR_SOUNDSHORTBEEP              140
#define IDR_SOUNDMEDIUMBEEP             141
#define IDR_SOUNDCREATENODE             142
#define IDR_SOUNDCREATELINK             144
#define IDD_CHECKRESULT                 145
#define IDD_CHANNELS1                   146
#define IDD_NODEPROPS                   146
#define IDR_SOUNDLONGBEEP               148
#define IDR_STARTUP                     149
#define IDD_POLICY                      150
#define IDD_ASSIGNDATA                  152
#define IDD_SENDDATA                    153
#define IDD_MANAGEDATA                  154
#define IDD_EVENTLIST                   156
#define IDC_ABOUT                       1001
#define IDC_SYSTEM                      1002
#define IDC_MACHINES                    1003
#define IDC_VERSION                     1004
#define IDC_DESC                        1005
#define IDC_TOTALMEM                    1006
#define IDC_MEMFREE                     1007
#define IDC_NUMMACHINES                 1008
#define IDC_MACHINEMEM                  1009
#define IDC_LOGO                        1011
#define IDC_MIN                         1015
#define IDC_ALLOW                       1016
#define IDC_CREATE                      1017
#define IDC_VIEWEVENTS                  1018
#define IDC_CONTROL                     1019
#define IDC_MACNUM                      1021
#define IDC_STACK                       1022
#define IDC_OUTCHANNEL                  1022
#define IDC_OUTPROPERTY                 1023
#define IDC_COLSPEED                    1023
#define IDC_INCHANNEL                   1024
#define IDC_HALFLIFE2                   1024
#define IDC_HALFLIFE                    1024
#define IDC_INPROPERTY                  1025
#define IDC_HALFLIFE3                   1025
#define IDC_DANDESERVER                 1025
#define IDC_SEC                         1026
#define IDC_INOUTSEC                    1026
#define IDC_LIST1                       1032
#define IDC_NODEID                      1033
#define IDC_NODECERTPROPS               1034
#define IDC_NODESECMAX                  1035
#define IDC_NODESECMIN                  1036
#define IDC_ROTATESEL                   1037
#define IDC_TEMPLATEINT                 1037
#define IDC_SELSPEED                    1038
#define IDC_ADHOCTX                     1038
#define IDC_CHECK_FIREWALL              1039
#define IDC_SOUND                       1039
#define IDC_CHECK_IDS                   1040
#define IDC_ROTATESEL2                  1040
#define IDC_SCREENSHOT                  1040
#define IDC_COMBO_EA                    1041
#define IDC_DANDELION                   1041
#define IDC_NODENAME                    1042
#define IDC_COMBO_SS                    1043
#define IDC_COMBO_SL                    1044
#define IDC_COMBOBOXEX1                 1045
#define IDC_ADHOCRX                     1045
#define IDC_RICHEDIT21                  1046
#define IDC_TEMPLATESTRING              1046
#define IDC_CHECK_EXTERNAL              1047
#define IDC_CHECK_ADHOC                 1048
#define IDC_POLICY1                     1049
#define IDC_TEMPLATEBOOL                1049
#define IDC_POLICY2                     1050
#define IDC_TEMPLATEFLOAT               1051
#define IDC_LIST2                       1052
#define IDC_ASSIGNEDDATA                1052
#define IDC_DATAINXML                   1052
#define IDC_BUTTON1                     1053
#define IDC_ADDDATA                     1053
#define IDC_MODIFY_DATA                 1053
#define IDC_TEMPLATEOPTION              1053
#define IDC_BUTTON2                     1054
#define IDC_REMOVEDATA                  1054
#define IDC_ADD_DATA                    1054
#define IDC_AVAILABLEDATA               1057
#define IDC_FILELIST                    1058
#define IDC_COMBO2                      1059
#define IDC_NODELIST                    1059
#define IDC_COMBO_UPDATESL              1059
#define IDC_DATETIMEPICKER1             1060
#define IDC_EDIT_FILENAME               1064
#define IDC_COMBO_ADDSL                 1066
#define IDC_BUTTON3                     1068
#define IDC_DELETE_DATA                 1068
#define IDC_SLCHANNEL                   1069
#define IDC_EVENTLIST                   1071
#define IDC_SLIDER_ADHOCTX              1074
#define IDC_SLIDER2                     1075
#define IDC_SLIDER_ADHOCRX              1075
#define IDC_LABEL                       1076
#define IDC_TEMPLATELABEL               1077
#define ID_FILE_NEWVIRTUALMACHINE       40001
#define ID_FILE_EXIT                    40002
#define ID_CURRENTMACHINE_LOADPROGRAM   40003
#define ID_CURRENTMACHINE_CLEARCONSOLE  40004
#define ID_CURRENTMACHINE_SAVEPROGRAM   40005
#define ID_HELP_ABOUT                   40006
#define ID_CURRENTMACHINE_CLOSEMACHINE  40007
#define ID_HELP_MACHINESTATISTICS       40008
#define ID_VIEW_CLEARCONSOLE            40009
#define ID_VIEW_OPTIONS                 40010
#define ID_HELP_CONTENTS                40011
#define ID_CURRENTMACHINE_ENDPROGRAM    40012
#define ID_MENU_SHOW                    40013
#define ID_MENU_ABOUT                   40014
#define ID_MENU_EXIT                    40015
#define ID_CHANNELS                     40017
#define ID_TOPOLOGY_DELETELINK          40018
#define ID_TOPOLOGY_PETRIFY             40019
#define ID_CURRENTMACHINE_PAUSEPROGRAM  40021
#define ID_TOPOLOGY_REANIMATE           40022
#define ID_TOPOLOGY_ANALYSE             40023
#define ID_TOPOLOGY_LOADXML             40024
#define ID_TOPOLOGY_ANALYSETOPOLOGY     40025
#define ID_TOPOLOGY_SHOWRESULTS         40026
#define ID_Menu                         40027
#define ID_VIEW_SELECT                  40028
#define ID_VIEW_CREATENODE              40030
#define ID_VIEW_CREATELINK              40031
#define ID_VIEW_ROTATE                  40032
#define ID_BUTTON_SELECT                40033
#define ID_BUTTON_ROTATE                40038
#define ID_BUTTON_CREATE_HOSPITAL       40039
#define ID_BUTTON_CREATELINK            40040
#define ID_VIEW_SPIN                    40044
#define ID_BUTTON40045                  40045
#define ID_BUTTON40046                  40046
#define ID_BUTTON_SHOWINFO              40046
#define ID_BUTTON_SPIN                  40047
#define ID_NODEPROPS                    40050
#define ID_BUTTON_POINTTOSELECTED       40051
#define ID_VIEW_POINTTOSELECTED         40052
#define ID_VIEW_REE                     40053
#define ID_Menu40054                    40054
#define ID_TOPOLOGY_RESET               40055
#define ID_VIEW_VIEWOPTIONS             40056
#define ID_VIEW_OVERLAY                 40057
#define ID_BUTTON_CREATE_POLICE         40059
#define ID_BUTTON40060                  40060
#define ID_BUTTON_CREATE_BANK           40060
#define ID_VIEW_CREATE_HOSPITAL         40061
#define ID_VIEW_CREATE_POLICE           40062
#define ID_MENU_NODEPROPERTIES          40063
#define ID_VIEW_OPENCONSOLE             40064
#define ID_TOPOLOGY_DELETENODE          40067
#define ID_FILE_SAVE_TOPOLOGY           40068
#define ID_FILE_LOAD                    40069
#define ID_HELP_POLICY                  40070
#define ID_BUTTON_CREATE_EVENT          40071
#define ID_BUTTON_CREATE_MOBILE         40072
#define ID_BUTTON_CREATE_RESCUE         40073
#define ID_BUTTON_CREATE_FIRE           40074
#define ID_BUTTON_CREATE_AMBULANCE      40075
#define ID_VIEW_CREATE_BANK             40083
#define ID_VIEW_CREATE_EVENT            40084
#define ID_VIEW_CREATE_MOBILE           40085
#define ID_VIEW_CREATE_RESCUE           40086
#define ID_VIEW_CREATE_FIRE             40087
#define ID_CURRENTMACHINE_CLEARVM       40088
#define ID_VIEW_CREATE_AMBULANCE        40088
#define ID_CREATENODE_DEPTOFTRANSPORT   40089
#define ID_VIEW_CREATE_TRANSPORT        40090
#define ID_BUTTON_CREATE_TRANSPORT      40091
#define ID_TOPOLOGY_ASSIG               40092
#define ID_TOPOLOGY_ASSIGNDATA          40093
#define ID_TOPOLOGY_SENDDATA            40094
#define ID_TOPOLOGY_MANAGEDATA          40095
#define ID_EVENTS_RESETTIME             40096
#define ID_EVENTS_EVENTLIST             40097
#define ID_EVENTS_SHOWEVENTLIST         40098
#define ID_VIEW_RUNSERVER               40099
#define ID_VIEW_STOPSERVER              40100
#define ID_FILE_SCENE                   40101
#define ID_SCENE_TRON                   40102
#define ID_SCENE_JMUMAP                 40103
#define ID_SCENE_LANDMARKS              40104
#define ID_SCENE_STJOHN                 40105
#define ID_BUTTON_EXTERNAL              40106
#define ID_VIEW_CREATE_EXTERNAL         40107
#define ID_EVENTS_RESETCLEAR            40108
#define ID_Menu40109                    40109
#define ID_Menu40110                    40110
#define ID_LOAD_SCENE                   40111
#define ID_SCENE_LOAD                   40112
#define ID_TOOLS_NETWORKVIEW            40113
#define ID_VIEW_RENDERTYPE              40114
#define ID_TEST                         40115
#define ID_MENU_FILE                    40116
#define ID_MENU_TOOLS                   40117
#define ID_MENU_TOPOLOGY                40118
#define ID_MENU_PROGRAM                 40119
#define ID_MENU_EVENTS                  40120
#define ID_MENU_HELP                    40121
#define ID_TOOLS_FULLSCREEN             40122
#define ID_FULLSCREEN                   40123
#define ID_TOPOLOGY_PROPERTSET          40124
#define ID_PROPERTSET                   40125
#define ID_PROPERTYSET                  40126
#define ID_PROPERTIES                   40127
#define ID_FILE_OPENDEFAULTPROPERTYSET  40128
#define ID_OPENDEFAULTPROPERTYSET       40129
#define ID_FILE_OPENDEFAULTPROPERTYSET40130 40130
#define ID_FILE_OPEN40131               40131
#define ID_FILE_OPEN40132               40132

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40133
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
